import type { Scheme } from "@/types";

export const schemeCatalog: Scheme[] = [
  {
    id: "pm-kisan",
    slug: "pm-kisan",
    name: "PM Kisan Samman Nidhi",
    ministry: "Ministry of Agriculture & Farmers Welfare",
    type: "Central",
    category: "Agriculture",
    benefit: "Provides income support to eligible farmer families in three instalments every year.",
    annualBenefit: "₹6,000/year",
    howToApply: "Apply on the PM-KISAN portal or through your nearest CSC with Aadhaar and land records.",
    documents: ["Aadhaar Card", "Bank Account", "Land Record"],
    applyUrl: "https://pmkisan.gov.in/",
    deadline: "Ongoing",
    overview: "PM Kisan is a direct benefit transfer scheme that supports small and medium farmer households.",
    eligibility: ["Farmer family", "Valid land record", "Indian resident"],
    tags: ["Farmer", "Income Support", "Direct Benefit"]
  },
  {
    id: "ayushman-bharat",
    slug: "ayushman-bharat",
    name: "Ayushman Bharat PM-JAY",
    ministry: "Ministry of Health and Family Welfare",
    type: "Central",
    category: "Health",
    benefit: "Offers cashless hospitalisation cover for eligible families at empanelled hospitals.",
    annualBenefit: "₹5,00,000/year",
    howToApply: "Check eligibility on the PM-JAY portal and complete verification at a listed hospital or camp.",
    documents: ["Aadhaar Card", "Ration Card", "Mobile Number"],
    applyUrl: "https://pmjay.gov.in/",
    deadline: "Ongoing",
    overview: "A flagship health assurance scheme that reduces catastrophic healthcare costs for vulnerable families.",
    eligibility: ["Eligible household", "PM-JAY database match"],
    tags: ["Insurance", "Hospital Cover", "Family Health"]
  },
  {
    id: "pmay-urban",
    slug: "pmay-urban",
    name: "Pradhan Mantri Awas Yojana - Urban",
    ministry: "Ministry of Housing and Urban Affairs",
    type: "Central",
    category: "Housing",
    benefit: "Supports first-time home buyers and urban low-income households through housing assistance and interest subsidy.",
    annualBenefit: "₹2,67,000/year",
    howToApply: "Apply through the PMAY-U portal or your urban local body with income proof and home ownership details.",
    documents: ["Aadhaar Card", "Income Certificate", "Address Proof"],
    applyUrl: "https://pmaymis.gov.in/",
    deadline: "Ongoing",
    overview: "PMAY-U helps economically weaker and middle-income families access affordable urban housing.",
    eligibility: ["Urban resident", "No pucca house", "Income-based category"],
    tags: ["Housing", "Urban", "Interest Subsidy"]
  },
  {
    id: "national-scholarship-portal",
    slug: "national-scholarship-portal",
    name: "National Scholarship Portal",
    ministry: "Ministry of Electronics & IT",
    type: "Central",
    category: "Education",
    benefit: "Aggregates multiple scholarships for students from minority, SC, ST, OBC, and low-income backgrounds.",
    annualBenefit: "₹75,000/year",
    howToApply: "Register on the NSP portal, complete your profile, upload academic documents, and submit your application.",
    documents: ["Aadhaar Card", "Income Certificate", "Marksheet"],
    applyUrl: "https://scholarships.gov.in/",
    deadline: "Seasonal",
    overview: "A single-window platform for many central and state scholarships with streamlined application tracking.",
    eligibility: ["Student", "Eligible category", "Academic enrolment"],
    tags: ["Student", "Scholarship", "Education"]
  },
  {
    id: "maji-ladki-bahin",
    slug: "maji-ladki-bahin",
    name: "Mukhyamantri Majhi Ladki Bahin Yojana",
    ministry: "Government of Maharashtra",
    type: "State",
    state: "Maharashtra",
    category: "Women",
    benefit: "Provides direct monthly assistance to eligible women in Maharashtra.",
    annualBenefit: "₹18,000/year",
    howToApply: "Apply through the official state portal or nearby facilitation centre with domicile and bank details.",
    documents: ["Aadhaar Card", "Domicile Certificate", "Bank Passbook"],
    applyUrl: "https://ladakibahin.maharashtra.gov.in/",
    deadline: "Ongoing",
    overview: "A Maharashtra state support program focused on improving the financial independence of women.",
    eligibility: ["Woman applicant", "Maharashtra resident", "Income threshold applies"],
    tags: ["Women", "Maharashtra", "Direct Benefit"]
  },
  {
    id: "mahatma-jyotiba-phule-jan-arogya",
    slug: "mahatma-jyotiba-phule-jan-arogya",
    name: "Mahatma Jyotiba Phule Jan Arogya Yojana",
    ministry: "Government of Maharashtra",
    type: "State",
    state: "Maharashtra",
    category: "Health",
    benefit: "Provides cashless healthcare support for eligible residents of Maharashtra.",
    annualBenefit: "₹1,50,000/year",
    howToApply: "Confirm eligibility at a network hospital and complete biometric verification with identity proof.",
    documents: ["Aadhaar Card", "Ration Card", "Residence Proof"],
    applyUrl: "https://www.jeevandayee.gov.in/",
    deadline: "Ongoing",
    overview: "A state-backed health coverage scheme for families who need affordable access to treatment.",
    eligibility: ["Maharashtra resident", "Eligible family category"],
    tags: ["Health", "Maharashtra", "Hospital Care"]
  },
  {
    id: "pm-svanidhi",
    slug: "pm-svanidhi",
    name: "PM SVANidhi",
    ministry: "Ministry of Housing and Urban Affairs",
    type: "Central",
    category: "Livelihood",
    benefit: "Offers working capital support to street vendors with incentives for digital repayments.",
    annualBenefit: "₹50,000/year",
    howToApply: "Apply with your urban local body certificate or vendor ID through the PM SVANidhi portal.",
    documents: ["Aadhaar Card", "Vendor Certificate", "Bank Account"],
    applyUrl: "https://pmsvanidhi.mohua.gov.in/",
    deadline: "Ongoing",
    overview: "A micro-credit scheme helping street vendors restart and expand their businesses.",
    eligibility: ["Street vendor", "Urban local body identification"],
    tags: ["Vendor", "Loan", "Livelihood"]
  },
  {
    id: "atal-pension-yojana",
    slug: "atal-pension-yojana",
    name: "Atal Pension Yojana",
    ministry: "Ministry of Finance",
    type: "Central",
    category: "Insurance",
    benefit: "Builds a guaranteed pension for workers in the unorganised sector through low monthly contributions.",
    annualBenefit: "₹60,000/year",
    howToApply: "Visit your bank or post office, choose your pension slab, and enrol with Aadhaar-linked details.",
    documents: ["Aadhaar Card", "Savings Account", "Mobile Number"],
    applyUrl: "https://enps.nsdl.com/eNPS/NationalPensionSystem.html",
    deadline: "Ongoing",
    overview: "A pension-focused social security scheme designed for long-term retirement stability.",
    eligibility: ["Age 18 to 40", "Savings account holder"],
    tags: ["Pension", "Unorganised Workers", "Retirement"]
  }
];

export function getSchemeBySlug(slug: string) {
  return schemeCatalog.find((scheme) => scheme.slug === slug || scheme.id === slug);
}
